name: CI

on: push

permissions:
  contents: read
  packages: read

jobs:
  cache-hash:
    name: Calculate Cache Hash
    runs-on: ubuntu-26.04
    outputs:
      hash: ${{ steps.hash.outputs.hash }}
    steps:
      - uses: actions/checkout@v7
      - name: Calculate hash
        id: hash
        run: |
          echo "hash=${{ hashFiles(
            '**/CMakeLists.txt',
            '**/*.cmake',
            '**/*.in',
            'vendored/**',
            'CMakePresets.json',
            'ci/containers/debian.Containerfile'
          ) }}" >> "$GITHUB_OUTPUT"
  build:
    name: Build (${{ matrix.arch }}, ${{ matrix.compiler }})
    needs: cache-hash
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
        arch: [x86_64, aarch64]
        include:
          - arch: x86_64
            runner: ubuntu-26.04
          - arch: aarch64
            runner: ubuntu-26.04-arm
    container: ghcr.io/${{ github.repository }}-ci:debian
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v7
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - uses: actions/cache@v6
        with:
          path: build
          key: cmake-build-${{ matrix.arch }}-${{ matrix.compiler }}-${{ needs.cache-hash.outputs.hash }}
      - name: Build
        run: |
          cmake --preset ci-${{ matrix.compiler }}
          cmake --build --preset ci-${{ matrix.compiler }}
  build-appimage:
    name: Build AppImage (${{ matrix.arch }})
    needs: cache-hash
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            runner: ubuntu-26.04
          - arch: aarch64
            runner: ubuntu-26.04-arm
    container: ghcr.io/${{ github.repository }}-ci:debian
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v7
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - uses: actions/cache@v6
        with:
          path: build-appimage
          key: cmake-appimage-${{ matrix.arch }}-${{ needs.cache-hash.outputs.hash }}
      - name: Build
        run: |
          cmake --preset appimage
          cmake --build --preset appimage
    # TODO: build and upload the appimage as an artifact
  test:
    name: Unit Tests (${{ matrix.arch }})
    needs: cache-hash
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            runner: ubuntu-26.04
          - arch: aarch64
            runner: ubuntu-26.04-arm
    container: ghcr.io/${{ github.repository }}-ci:debian
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v7
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - uses: actions/cache@v6
        with:
          path: build
          key: cmake-test-${{ matrix.arch }}-${{ needs.cache-hash.outputs.hash }}
      - name: Build and run tests
        run: |
          cmake --workflow --preset test
