name: CI

on: push

jobs:
  build:
    name: Build (${{ matrix.arch }}, ${{ matrix.compiler }})
    strategy:
      matrix:
        compiler: [gcc, clang]
        include:
          - runner: ubuntu-26.04
            arch: x86_64
          - runner: ubuntu-26.04-arm
            arch: aarch64
    container: ghcr.io/${{ github.repository }}-ci:debian
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v7
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Build
        run: |
          cmake --preset ci-${{ matrix.compiler }}
          cmake --build --preset ci-${{ matrix.compiler }}
  build-appimage:
    name: Build AppImage (${{ matrix.arch }})
    strategy:
      matrix:
        include:
          - runner: ubuntu-26.04
            arch: x86_64
          - runner: ubuntu-26.04-arm
            arch: aarch64
    container: ghcr.io/${{ github.repository }}-ci:debian
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v7
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Build
        run: |
          cmake --preset appimage
          cmake --build --preset appimage
    # TODO: build and upload the appimage as an artifact
  test:
    name: Unit Tests (${{ matrix.arch }})
    strategy:
      matrix:
        include:
          - runner: ubuntu-26.04
            arch: x86_64
          - runner: ubuntu-26.04-arm
            arch: aarch64
    container: ghcr.io/${{ github.repository }}-ci:debian
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v7
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Build and run tests
        run: |
          cmake --workflow --preset test
