name: Rebuild CI Container

on:
  workflow_dispatch:
  push:
    paths: ['ci/containers/debian.Containerfile']

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build and push to ghcr.io
    uses: docker/github-builder/.github/workflows/build.yml@v1
    with:
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      meta-images: ghcr.io/${{ github.repository }}-ci
      meta-tags: |
        type=raw,value=debian
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
