name: Rebuild CI Container

on:
  workflow_dispatch:
  push:
    paths: ['ci/containers/debian.Containerfile']

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build and push to ghcr.io
    strategy:
      matrix:
        include:
          - runner: ubuntu-26.04
            arch: amd64
          - runner: ubuntu-26.04-arm
            arch: arm64
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Login to ghcr
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          platforms: linux/${{ matrix.arch }}
          file: ci/containers/debian.Containerfile
          push: true
          tags: ghcr.io/${{ github.repository }}-ci:debian-${{ matrix.arch }}
  manifest:
    name: Create multi-arch manifest
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to ghcr
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Create manifest
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/${{ github.repository }}-ci:debian \
            ghcr.io/${{ github.repository }}-ci:debian-amd64 \
            ghcr.io/${{ github.repository }}-ci:debian-arm64
